name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Trigger workflow only when pushing tags like v1.0.0

jobs:
  pypi-publish:
    name: Upload Release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # Required for Trusted Publishing
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (Python 3.8)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8  # Set Python version to 3.8

      # Step 3: Upgrade pip and install build tools
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build

      # Step 4: Build the distribution files (sdist and wheel)
      - name: Build distributions
        run: python -m build

      # Step 5: Publish the distribution files to PyPI
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
